-- =============================================================
-- The Blues Collective — seed data
-- Run this AFTER schema.sql, in Supabase SQL Editor. Safe to re-run.
-- =============================================================
--
-- NOTE (Phase 2): the squad and fixtures are now filled by the daily sync jobs
-- (API-Football for the squad, football-data.org for fixtures + table) and the
-- database is the single source of truth. We no longer seed hand-typed squad
-- rows or placeholder fixtures here — those were the stale data that made the
-- site look wrong. Pre-season friendlies are added by hand at /admin/fixtures.
--
-- This file is intentionally left with no inserts. Demo posts/articles/rebuilds
-- are still created from within the app (they need a logged-in user).
